import type {VariableSpec} from '@caton-ai/core';

export const VARIABLES: readonly VariableSpec[] = [
  {
    key: 'imap-host',
    label: 'IMAP server',
    kind: 'text',
    required: true,
    default: 'imap.gmail.com',
    help: 'The IMAP server of the mailbox. For Gmail and Google Workspace it is `imap.gmail.com`. Only encrypted connections (TLS) are used.',
  },
  {
    key: 'imap-port',
    label: 'IMAP port',
    kind: 'number',
    required: true,
    default: 993,
    help: 'The TLS port of the IMAP server; almost always `993`.',
  },
  {
    key: 'imap-user',
    label: 'Email address',
    kind: 'text',
    required: true,
    help: 'The address of the mailbox that receives the alerts, such as `me@example.com`.',
  },
  {
    key: 'imap-password',
    label: 'App password',
    kind: 'secret',
    required: true,
    help: [
      'An **app password** for this mailbox, never your usual password.',
      '- **Gmail and Google Workspace:** 2-Step Verification must be on. Create the password at [Google Account → App passwords](https://myaccount.google.com/apppasswords). In Google Workspace, the administrator must also allow IMAP access.',
      '- **Other providers:** look for "app passwords" in the security settings of your account.',
      'The password opens the whole mailbox, but Catón AI only reads the folder you choose: it never marks, moves or deletes an email. When several mailboxes of the same account are configured, save it once as a **shared secret** and write `${its-name}` in each.',
    ].join('\n\n'),
  },
  {
    key: 'imap-folder',
    label: 'Folder',
    kind: 'text',
    required: false,
    help: 'The folder to read. When empty, the folder holding all mail (Gmail\'s "All Mail") is read, or the inbox if there is none.',
  },
  {
    key: 'auth-server',
    label: 'Trusted receiving server',
    kind: 'text',
    required: true,
    default: 'mx.google.com',
    help: [
      'The server that receives your email and checks that each message really comes from its sender (DKIM and DMARC). Only messages it verified are read, so a forged alert is never taken as a real charge.',
      'For Gmail and Google Workspace it is `mx.google.com`.',
    ].join('\n\n'),
  },
  {
    key: 'model',
    label: 'Language model',
    kind: 'model',
    required: false,
    help: [
      'The model that reads the emails that pass the local filter. Only emails from senders your mail server authenticated, that mention an amount and a word about money, are sent to it; your own emails never are.',
      'Until one is chosen nothing is sent: each sync only counts, per sender, the emails a model would read, so you can see the volume first.',
    ].join('\n\n'),
  },
  {
    key: 'effort',
    label: 'Thinking effort',
    kind: 'effort',
    required: false,
    help: 'How much the model thinks about each email. Receipts and alerts are simple: a low effort is usually enough and costs less.',
  },
  {
    key: 'backfill-days',
    label: 'Days to read back',
    kind: 'number',
    required: true,
    default: 90,
    help: 'How far back the first sync reads. Later syncs read only the emails received since the last one.',
  },
  {
    key: 'max-per-sync',
    label: 'Emails per sync',
    kind: 'number',
    required: true,
    default: 50,
    help: 'The most emails sent to the model in one sync; the rest are read by the next ones. It bounds what one sync can cost.',
  },
  {
    key: 'card-senders',
    label: 'Cards read only by email',
    kind: 'list',
    required: false,
    help: [
      'The sender domains of card alerts for cards no bank connection reads, such as `americanexpress.com`. Their charges and refunds become movements of that card; every other email only adds documents, such as receipts, to what the banks report.',
      'The card is recognised by the domain that authenticated the email, never by what the email says, so a forged alert cannot add movements.',
    ].join('\n\n'),
  },
  {
    key: 'card-currency',
    label: 'Currency of those cards',
    kind: 'text',
    required: false,
    default: 'EUR',
    help: 'The ISO 4217 code of the cards above, such as `EUR`.',
  },
];
