import {reports} from './text-reports.ts';

/** Every string of the interface, in one place, ready for translation. */
export const text = {
  product: 'Catón AI',
  tagline: 'Your financial watchdog, running on this computer only',
  loading: 'Loading…',
  signedOut: {
    title: 'Sign in from your terminal',
    body: 'Open the one-time link printed by caton serve. Each link works once, for ten minutes.',
  },
  lock: 'Lock',
  store: {
    createTitle: 'Create your secret store',
    createIntro:
      'Passwords and keys are kept encrypted. Choose where the key that opens them lives; losing it loses every secret.',
    modes: {
      passphrase: ['Passphrase', 'Most secure. You type it once each time Catón AI starts.'],
      file: ['Key file', 'Opens by itself. For servers, or a container secret under /run/secrets.'],
      'os-store': [
        'Operating system',
        'Opens by itself, with the key kept by macOS Keychain or Linux Secret Service.',
      ],
    },
    passphrase: 'Passphrase',
    repeat: 'Repeat the passphrase',
    keyFile: 'Absolute path of the key file',
    create: 'Create the store',
    tooShort: (minimum: number) => `Use at least ${String(minimum)} characters.`,
    mismatch: 'The passphrases do not match.',
    unlockTitle: 'Unlock your secret store',
    unlock: 'Unlock',
    unlockFailed: 'The store could not open by itself:',
  },
  configuration: {
    title: 'Connections',
    intro: 'Each connection is one use of a plugin, such as one bank or one mailbox.',
    empty: 'No connections yet.',
    add: 'Add a connection',
    edit: 'Edit',
    plugin: 'Plugin',
    save: 'Save',
    cancel: 'Cancel',
    secretReady: 'A new value will be saved.',
    useShared: 'Or use a shared secret',
    noShared: 'Choose…',
    ownValue: 'No, its own value',
    listHint: 'Separate values with commas.',
    needs: (labels: readonly string[]) => `Needs: ${labels.join(', ')}`,
    loadFile: 'Load from a file',
  },
  editor: {
    connector: {
      newTitle: 'New connection',
      editTitle: (title: string) => `Edit ${title}`,
      name: 'Connection name',
      nameHelp:
        'How you call this connection. Its identifier is made from the first name you give it and never changes.',
      remove: 'Remove connection',
      confirmRemove: 'Confirm: remove this connection',
    },
    model: {
      newTitle: 'New language model',
      editTitle: (title: string) => `Edit ${title}`,
      name: 'Model name',
      nameHelp:
        'How connections list this model, such as "Claude for receipts". Its identifier is made from the first name you give it and never changes.',
      remove: 'Remove model',
      confirmRemove: 'Confirm: remove this model',
    },
  },
  models: {
    title: 'Language models',
    intro:
      "The models connections can use to read text, from any provider. A provider's key is asked once, saved encrypted, and reused by all its models.",
    empty: 'No language models yet.',
    add: 'Add a language model',
    columns: ['Model', 'Settings', 'Status', 'Used by'],
    ready: 'Ready',
    unused: 'No connection',
    choose: 'Choose a model…',
    none: 'No language model yet: add one under Language models first.',
  },
  effort: {
    'provider-default': "Provider's default",
    none: 'None: answer directly',
    minimal: 'Minimal',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    xhigh: 'Maximum',
  },
  providerKey: {
    saved: (name: string) => `Saved as ${name}`,
    replace: 'Replace the key',
    willSave: (name: string) =>
      `Saved encrypted as ${name} and reused by every model of this provider.`,
  },
  reports,
  sync: {
    all: 'Sync all',
    button: 'Sync',
    one: (title: string) => `Sync ${title}`,
    running: 'Syncing…',
    changed: 'Changed since this sync: sync again to see the result of your changes.',
  },
  connections: {
    title: 'Connections',
    empty: 'No connections configured yet.',
    columns: ['Connection', 'Plugin', 'Status', 'Last sync', 'Problem'],
    outcome: {ok: 'Synced', failed: 'Failing', never: 'Never synced'},
  },
  secrets: {
    title: 'Shared secrets',
    intro:
      'Values several connections can use, such as one app password for several mailboxes. Each connection keeps a reference to the shared secret, never a copy: replacing it here updates them all. Values are encrypted and never shown.',
    empty: 'No shared secrets yet.',
    missing: 'Missing',
    stored: 'Stored',
    macro: (target: string) => `Uses the shared secret ${target}`,
    macroMissing: (target: string) => `Uses the shared secret ${target}, which is missing`,
    ownValue: 'Own value saved',
    usedBy: (owners: readonly string[]) => `Used by ${owners.join(', ')}`,
    unused: 'Not used by any connection',
    valueOf: (name: string) => `Value of ${name}`,
    saveValue: 'Save',
    fromFile: (name: string) => `Load ${name} from a file`,
    replace: 'Replace',
    cancel: 'Cancel',
    remove: 'Remove',
    confirm: 'Confirm removal',
    confirmUsed: (owners: readonly string[]) => `Remove, breaking ${owners.join(', ')}`,
    addTitle: 'Add a shared secret',
    addIntro: 'Name it, then choose it in each connection under "Or use a shared secret".',
    name: 'Name',
    value: 'Value',
    save: 'Save secret',
    invalidName: 'Use lowercase letters, digits and dashes.',
  },
} as const;
