/** Every string of the interface, in one place, ready for translation. */
export const text = {
  product: 'Catón AI',
  tagline: 'Your financial watchdog, running on this computer only',
  loading: 'Loading…',
  signedOut: {
    title: 'Sign in from your terminal',
    body: 'Open the one-time link printed by caton serve. Each link works once, for ten minutes.',
  },
  lock: 'Lock',
  store: {
    createTitle: 'Create your secret store',
    createIntro:
      'Passwords and keys are kept encrypted. Choose where the key that opens them lives; losing it loses every secret.',
    modes: {
      passphrase: ['Passphrase', 'Most secure. You type it once each time Catón AI starts.'],
      file: ['Key file', 'Opens by itself. For servers, or a container secret under /run/secrets.'],
      'os-store': [
        'Operating system',
        'Opens by itself, with the key kept by macOS Keychain or Linux Secret Service.',
      ],
    },
    passphrase: 'Passphrase',
    repeat: 'Repeat the passphrase',
    keyFile: 'Absolute path of the key file',
    create: 'Create the store',
    tooShort: (minimum: number) => `Use at least ${String(minimum)} characters.`,
    mismatch: 'The passphrases do not match.',
    unlockTitle: 'Unlock your secret store',
    unlock: 'Unlock',
    unlockFailed: 'The store could not open by itself:',
  },
  configuration: {
    title: 'Connections',
    intro: 'Each connection is one use of a plugin, such as one bank or one mailbox.',
    empty: 'No connections yet.',
    add: 'Add a connection',
    edit: 'Edit',
    newTitle: 'New connection',
    editTitle: (title: string) => `Edit ${title}`,
    plugin: 'Plugin',
    name: 'Connection name',
    nameHelp:
      'How you call this connection. Its identifier is made from the first name you give it and never changes.',
    save: 'Save',
    cancel: 'Cancel',
    remove: 'Remove connection',
    confirmRemove: 'Confirm: remove this connection',
    secretReady: 'A new value will be saved.',
    useShared: 'Or use a shared secret',
    noShared: 'Choose…',
    listHint: 'Separate values with commas.',
    loadFile: 'Load from a file',
  },
  connections: {
    title: 'Connections',
    empty: 'No connections configured yet.',
    columns: ['Connection', 'Plugin', 'Status', 'Last sync', 'Problem'],
    outcome: {ok: 'Synced', failed: 'Failing', never: 'Never synced'},
  },
  secrets: {
    title: 'Secrets',
    intro:
      'Values are kept encrypted and can be replaced, never shown. To share one secret between several connections, save it once under a name of your choice and enter ${that-name} as their value.',
    empty: 'No secrets yet.',
    missing: 'Missing',
    stored: 'Stored',
    macro: (target: string) => `Uses the shared secret ${target}`,
    usedBy: (owners: readonly string[]) => `Used by ${owners.join(', ')}`,
    unused: 'Not used by any connection',
    valueOf: (name: string) => `Value of ${name}`,
    saveValue: 'Save',
    fromFile: (name: string) => `Load ${name} from a file`,
    replace: 'Replace',
    cancel: 'Cancel',
    remove: 'Remove',
    confirm: 'Confirm removal',
    confirmUsed: (owners: readonly string[]) => `Remove, breaking ${owners.join(', ')}`,
    addTitle: 'Add a shared secret',
    addIntro:
      'A value several connections can use, such as one app password for several mailboxes. Name it, then choose it in each connection under "Or use a shared secret".',
    name: 'Name',
    value: 'Value',
    save: 'Save secret',
    invalidName: 'Use lowercase letters, digits and dashes.',
  },
} as const;
